name: highcharts_options
version: 0.2.1+5
author: Gonzalo Pezzi <gonzalopezzi@gmail.com>
description: Highcharts Options contains base classes for wrapping the highcharts js api. If you want to use highcharts in Dart, use the highcharts packages for polymer or angular. I strongly recommend you using the Polymer version.
homepage: https://github.com/gonzalopezzi
dependencies:
  polymer: '>=0.15.0 <0.16.0'
  uuid: '>=0.5.0 <0.6.0'
dev_dependencies:
  unittest: any
