name: highcharts
version: 2.0.0
author: Gonzalo Pezzi <gonzalopezzi@gmail.com>
description: Highcharts API wrapped via JS interop (js package).
homepage: https://github.com/gonzalopezzi
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  uuid: any
  js: any
dev_dependencies:
  test: ^1.0.0