name: 'demo_highcharts_options'
version: 0.0.2
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  highcharts:
    path: ../

dev_dependencies:
  build_web_compilers: ">=0.3.6 <0.5.0"
  build_runner: ">=0.8.10 <2.0.0"
